### ISSUE TITLE
Lacking run instructions

### ISSUE THREAD

**Issue by carloscip** [TennisBowling/openexecution#5]
Hi, I am not able to make it work neither on linux nor in macos. The .sh on linux extracts 3 folders, and inside the bin folder there is an openexecution binary. After running it it shows dependencies error, perhaps I'm not running it properly (just from a terminal `./bin/openexecution`). Also, is this production ready?

**Comment by TennisBowling** [comment]
You should use the rust version of this instead: https://github.com/TennisBowling/openexecution-oe
